session13_assignment/project/accounts/urls.py
from django.urls import path
from accounts	import views

app_name = 'accounts' 
urlpatterns = [
#	/accounts/
    path('',	views.home,	name = 'home'),
]

session13_assignment/project/blog/urls.py
from django.urls import path
from blog	import views

app_name = 'blog'
#	중복을 피하기 위한 url 네임스페이스

urlpatterns = [
#	/blog/
    path('',	views.home,	name = 'home'),
    path('new/',	views.new,	name="new"),
    path('detail/<int:post_pk>/',	views.detail,	name="detail"),
    path('update/<int:post_pk>/',	views.update,	name="update"),
    path('delete/<int:post_pk>/',	views.delete,	name="delete"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

session13_assignment/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

session13_assignment/project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
#	Create	your	models	here.
class Profile(models.Model):
    user	= models.OneToOneField(User,	on_delete=models.CASCADE)
    age	= models.PositiveIntegerField(help_text="User	Age",	 blank=True,	null=True)

session13_assignment/project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
# class Post(models.Model):
#     title	= models.CharField(max_length=200)
#     content	= models.TextField()
    
#     def __str__(self):
#         return self.title
    

#	Create	your	models	here.
class Post(models.Model):
#	모델 속성 : 데이터베이스 테이블의 컬럼 = 모델 클래스의 속성 = 모델 클래스의 필드 (ORM)
    title	= models.CharField(verbose_name='TITLE',	max_length=50)
#	CharField는 max_length가 필수. form에서 input tag
    content	= models.TextField()
#	TextField는 form에서 textarea tag
    create_dt = models.DateTimeField(auto_now_add=True)
#	auto_now_add는 생성 시각 기준으로 자동 생성
    update_dt = models.DateTimeField(auto_now=True)
#	auto_now는 저장 시각 기준으로 자동 생성
    author	= models.ForeignKey(User,	on_delete=models.CASCADE,	related_name="my_posts", null=True)
#	ForignKey는 1:N에서 N에서 설정. CASCADE가 있는 속성에 해당하는 데이터 삭제 시, 그를 포함하는 모든 객체 삭제. related_name은 역참조할 때 사용

    class Meta:			#	메타 데이터 : 데이터에 대한 데이터. Meta 내부 클래스를 정의해 사용
        verbose_name = 'post'
#	모델 객체의 별칭. 
        verbose_name_plural = 'posts'
#	별칭의 복수형 명칭
        ordering	= ('-create_dt',	'author')
#	모델 객체 리스트 출력시 정렬 기준. -면 내림차순. 위의 경우에는 create_dt 기준으로 내림차순 후 author 기준으로 오름차순

#	모델 메소드 : 클래스 메소드가 아니라 객체 메소드. 항상 self인자를 가지고 있으며, 테이블 단위가 아니라 레코드 단위에 영향을 미친다. (테이블 단위는 views에서 Post.objects.all() 등으로 사용)
    def __str__(self):
#	자신(객체)의 문자열 표현을 반환한다. 
#	return	self.title
        return f'{self.title}입니다.'

def get_absolute_url(self):
#	자신(객체)의 url을 반환한다. detail을 보여주는 경우 위 메소드를 사용하면 편하다. 
    return reverse(f'blog:post_detail',	args=[self.id])
#	create_dt기준으로 앞 뒤 객체 반환.

def get_previous(self):
    return self.get_previous_by_create_dt()

def get_next(self):
    return self.get_next_by_create_dt()

class Comment(models.Model):
    post	= models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author	= models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_comments")
    content	= models.TextField()
    create_dt = models.DateTimeField(auto_now_add=True)

class Meta:
    ordering	= ('-create_dt',	'post',	'author')

def __str__(self):
    return f'{self.author}-{self.content}'

session13_assignment/project/accounts/views.py
from django.shortcuts import render
#	Create	your	views	here.
def home(request):
    return render(request,	'accounts/home.html')
# Create your views here.

session13_assignment/project/blog/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from django.contrib import auth
from django.contrib.auth.models import User

#	Create	your	views	here.

def home(request):
    posts	= Post.objects.all()

    return render(request,	'blog/home.html',	{'posts':posts})

def new(request):
    if request.method == "POST":
        new_post = Post.objects.create(
            title = request.POST['title'],
            content = request.POST['content']
        )
        return redirect('blog:detail',	new_post.pk)

    return render(request,	'blog/new.html')

def detail(request,	post_pk):
    post	= Post.objects.get(pk=post_pk)

    return render(request,	'blog/detail.html',	{'post':post})

def update(request,	post_pk):
    post	= Post.objects.get(pk=post_pk)

    if request.method == 'POST':
        Post.objects.filter(pk=post_pk).update(
            title = request.POST['title'],
            content = request.POST['content']
        )
        return redirect('blog:detail',	post_pk)

    return render(request,	'blog/update.html',	{'post':post})

def delete(request,	post_pk):
    post	= Post.objects.get(pk=post_pk)
    post.delete()

    return redirect('blog:home')


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        exist_user = User.objects.filter(username=username)
        if exist_user:
           error = "이미 존재하는 유저입니다."
           return render(request, 'blog/registration/signup.html', {"error":error})
      
        new_user = User.objects.create_user(username=username, password=password)
        auth.login(request, new_user, backend='django.contrib.auth.backends.ModelBackend')

        return redirect('blog:home')
    
    return render(request, 'blog/registration/signup.html')

def login(request):
   if request.method == 'POST':
      username = request.POST['username']
      password = request.POST['password']
      user = auth.authenticate(username=username, password=password)
      if user is not None:
           auth.login(request, user, backend ="django.contrib.auth.backends.ModelBackend")
           return redirect(request.GET.get('next', '/'))
      error = "아이디 또는 비밀번호가 틀립니다"
      return render(request, 'blog/registration/login.html', {"error":error})
        
   return render(request, 'blog/registration/login.html')

def logout(request):
   auth.logout(request)
   return redirect('blog:home')

session13_assignment/project/accounts/templates/accounts/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div>
      <h1>독후감 블로그-회원관리</h1>
      <a href="{%	url 'blog:home'	%}">독후감 블로그</a>
    </div>
  </body>
</html>

session13_assignment/project/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'blog/base.css' %}" />
    {% block css %} {% endblock css %}
    <title>Document</title>
  </head>
  <body>
    <div class="title">{% block title %} {% endblock title %}</div>
    <div class="container">{% block content %} {% endblock content %}</div>

    {% if user.is_authenticated %}
    <span class="navbar__menu__item">Hello, {{user.username}}</span>
    <li class="navbar__menu__item">
      <a href="{% url 'blog:logout'%}">로그아웃</a>
    </li>
    {% else %}
    <li class="navbar__menu__item">
      <a href="{% url 'blog:login'%}">로그인</a>
    </li>
    <li class="navbar__menu__item">
      <a href="{% url 'blog:signup'%}">회원가입</a>
    </li>
    {% endif %}
  </body>
</html>

session13_assignment/project/blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div>
      <h2>제목</h2>
      <p>{{ post.title }}</p>
    </div>
    <div>
      <h2>내용</h2>
      <p>{{ post.content }}</p>
    </div>
    <a href="{%	url 'blog:home'	%}">홈으로</a>
    <a href="{%	url 'blog:update'	post.pk %}">수정하기</a>
    <a href="{%	url 'blog:delete'	post.pk %}">삭제하기</a>
  </body>
</html>

session13_assignment/project/blog/templates/blog/home.html
{% extends 'blog/base.html' %} {% block title %} HOME{% endblock %} {% block
css%} {% load static %} {% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>독후감 블로그</h1>
    <div>
      <ul>
        {% for post in posts %}
        <li>
          <a href="{%	url 'blog:detail'	post.pk %}">{{ post.title }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
    <a href="{%	url 'blog:new'	%}">글 쓰러가기</a>
  </body>
</html>
{% endblock %}

session13_assignment/project/blog/templates/blog/new.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <div>
        <label for="title">제목</label>
        <input
          type="text"
          id="title"
          name="title"
          placeholder="제목을 입력해주세요."
        />
      </div>
      <div>
        <label for="content">내용</label>
        <textarea
          name="content"
          id="content"
          cols="30"
          rows="10"
          placeholder="내용을 입력해주세요."
        ></textarea>
      </div>
      <button type="submit">작성하기</button>
    </form>
  </body>
</html>

session13_assignment/project/blog/templates/blog/update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <div>
        <label for="title">제목</label>
        <input type="text" id="title" name="title" value="{{	post.title }}" />
      </div>
      <div>
        <label for="content">내용</label>
        <textarea name="content" id="content" cols="30" rows="10">
{{	post.content }}</textarea
        >
      </div>
      <button type="submit">수정하기</button>
    </form>
  </body>
</html>